# Generated by Django 4.1.4 on 2022-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recharge_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('title', models.CharField(default=None, max_length=100)),
                ('ammount', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('recharge_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
