# Generated by Django 4.1.4 on 2022-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recharge_id',
            field=models.IntegerField(default=None),
        ),
    ]
